create table article
(
    articles_id      bigint UNSIGNED generated by default as identity,
    create_date      timestamp(6),
    last_modify_date timestamp(6),
    title varchar(55) not null,
    content TEXT not null,
    primary key (articles_id)
);
