version: "3.8"
services:
  h2:
    image: oscarfonts/h2
    container_name: h2-db
    restart: always
    ports:
      - "8082:81"   # 웹 콘솔 포트
      - "1521:1521"   # TCP 포트
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -ifNotExists"
    volumes:
      - h2-data:/opt/h2-data
volumes:
  h2-data: